{% set name = "h2" %}
{% set version = "2.6.2" %}
{% set sha256 = "af35878673c83a44afbc12b13ac91a489da2819b5dc1e11768f3c2406f740fe9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - hyperframe    >=5.1.0,<6
    - hpack         >=2.3,<4
    - enum34        >=1.1.6,<2  # [py2k]

test:
  imports:
    - h2

about:
  home: http://python-hyper.org/h2/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'HTTP/2 State-Machine based protocol implementation'
  dev_url: https://github.com/python-hyper/hyper-h2

extra:
  recipe-maintainers:
    - primozgodec
