appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: p+d3kkt7amBgmbp6au8XM1P1/0m1t2aRmodVgpLtj+ZuFicLUo+wsodFYnvlL4R+cVKY1PPTq2xqB0gIaZUFg5LJw4ERocxw6mrwLuyvDRNVvTuTT39x/mQfFHV8yczoO70qwyMbzDQpeUq5GTEf3wJeRWIM+UtW3mn+v/zT+WLxphpmsLzQ3sBQqczmqP+eibXC7Vu+QhuI/OEfC/ioQGH+u9oPmvyVxcxqMXbyliZisafW7hez43PmVHavMxhq2dF6zoTZc+8HCIVFvGqACsQpTwH1JwVbONfXsJihpci+7Z2CGrLsmZqOuJHeAe0vA9T+pvDMmIssbyVA23t5g6lbQtPKd/8v0vTtoD16hT0OhaYgppjOOs2K4g3nk/cUbvVBeiIK/cIXD7MQGx/NXfYCrM15IDTeFGD6LXI85wfWuUdlNb89wPY11lQyIlRQgpNI913UuE+A9LpFB8khYTJef93TD3TnTAWJFJ4QHhiyv9jXUuJFLA/mlGdK08x37CHNMnmNc+R8XOo/pOLODqXQqy/WwJpA14OesQ4zstHc1f1/pyZm1LHKXXy4yU8ePw6Gy8EgtNKTH5V+5G0+dRFm1m0kwEvBeotKBk5lRp8zm9amMB0fgeaJbNxPFGQdjFRhIyM1d7OIdq5SNY29sq1ZELyY0px0LGyxaqlxXrg=}
conda_forge_output_validation: true
